
package com.gamespace.views;

import java.awt.Color;

/**
 *
 * @author ilust
 */
public class AddGamesFrame extends javax.swing.JFrame {

    private GameSpace gameSpace;
    /**
     * Creates new form AddGamesFrame
     */
    public AddGamesFrame() {
        setUndecorated(true);
        initComponents();
        gameSpace= new GameSpace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddGames = new javax.swing.JPanel();
        comboBoxRating = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtFldGameNum = new javax.swing.JTextField();
        lblGameNum = new javax.swing.JLabel();
        lblGameTitle = new javax.swing.JLabel();
        txtFldGameTitle = new javax.swing.JTextField();
        lblMainDevelopers = new javax.swing.JLabel();
        txtFldMainDevelopers = new javax.swing.JTextField();
        lblPublishers = new javax.swing.JLabel();
        txtFldPublishers = new javax.swing.JTextField();
        lblGenres = new javax.swing.JLabel();
        lblGenres1 = new javax.swing.JLabel();
        lblGenres2 = new javax.swing.JLabel();
        comboBoxPlatform = new javax.swing.JComboBox<>();
        txtFldLink = new javax.swing.JTextField();
        lblLink = new javax.swing.JLabel();
        txtFldReleasedYear = new javax.swing.JTextField();
        lblReleasedDate = new javax.swing.JLabel();
        txtFldReleasedMonth = new javax.swing.JTextField();
        txtFldReleasedDay = new javax.swing.JTextField();
        lblSlash1 = new javax.swing.JLabel();
        lblSlash2 = new javax.swing.JLabel();
        radioBtnAction = new javax.swing.JRadioButton();
        radioBtnAdventures = new javax.swing.JRadioButton();
        radioBtnEducational = new javax.swing.JRadioButton();
        radioBtnRolePlaying = new javax.swing.JRadioButton();
        radioBtnRacing = new javax.swing.JRadioButton();
        radioBtnSimulation = new javax.swing.JRadioButton();
        radioBtnSports = new javax.swing.JRadioButton();
        radioBtnStrategy = new javax.swing.JRadioButton();
        btnAddGame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(859, 627));

        pnlAddGames.setBackground(new java.awt.Color(145, 49, 117));
        pnlAddGames.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        pnlAddGames.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlAddGames.setFocusCycleRoot(true);
        pnlAddGames.setPreferredSize(new java.awt.Dimension(867, 627));

        comboBoxRating.setBackground(new java.awt.Color(32, 38, 46));
        comboBoxRating.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        comboBoxRating.setForeground(new java.awt.Color(233, 232, 231));
        comboBoxRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        comboBoxRating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        comboBoxRating.setMinimumSize(new java.awt.Dimension(254, 22));

        jLabel1.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 232, 231));
        jLabel1.setText("Add Games");

        txtFldGameNum.setBackground(new java.awt.Color(32, 38, 46));
        txtFldGameNum.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldGameNum.setForeground(new java.awt.Color(233, 232, 231));
        txtFldGameNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldGameNum.setPreferredSize(new java.awt.Dimension(254, 42));

        lblGameNum.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblGameNum.setForeground(new java.awt.Color(233, 232, 231));
        lblGameNum.setText("Game No.");

        lblGameTitle.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblGameTitle.setForeground(new java.awt.Color(233, 232, 231));
        lblGameTitle.setText("Game Title");

        txtFldGameTitle.setBackground(new java.awt.Color(32, 38, 46));
        txtFldGameTitle.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldGameTitle.setForeground(new java.awt.Color(233, 232, 231));
        txtFldGameTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldGameTitle.setPreferredSize(new java.awt.Dimension(254, 42));

        lblMainDevelopers.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblMainDevelopers.setForeground(new java.awt.Color(233, 232, 231));
        lblMainDevelopers.setText("Main Developers");

        txtFldMainDevelopers.setBackground(new java.awt.Color(32, 38, 46));
        txtFldMainDevelopers.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldMainDevelopers.setForeground(new java.awt.Color(233, 232, 231));
        txtFldMainDevelopers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldMainDevelopers.setPreferredSize(new java.awt.Dimension(254, 42));

        lblPublishers.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblPublishers.setForeground(new java.awt.Color(233, 232, 231));
        lblPublishers.setText("Publishers");

        txtFldPublishers.setBackground(new java.awt.Color(32, 38, 46));
        txtFldPublishers.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldPublishers.setForeground(new java.awt.Color(233, 232, 231));
        txtFldPublishers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldPublishers.setPreferredSize(new java.awt.Dimension(254, 42));

        lblGenres.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblGenres.setForeground(new java.awt.Color(233, 232, 231));
        lblGenres.setText("Genres");

        lblGenres1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblGenres1.setForeground(new java.awt.Color(233, 232, 231));
        lblGenres1.setText("Platform");

        lblGenres2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblGenres2.setForeground(new java.awt.Color(233, 232, 231));
        lblGenres2.setText("Rating");

        comboBoxPlatform.setBackground(new java.awt.Color(32, 38, 46));
        comboBoxPlatform.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        comboBoxPlatform.setForeground(new java.awt.Color(233, 232, 231));
        comboBoxPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Play Station", "XBox" }));
        comboBoxPlatform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        comboBoxPlatform.setMinimumSize(new java.awt.Dimension(254, 22));

        txtFldLink.setBackground(new java.awt.Color(32, 38, 46));
        txtFldLink.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldLink.setForeground(new java.awt.Color(233, 232, 231));
        txtFldLink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldLink.setPreferredSize(new java.awt.Dimension(254, 42));

        lblLink.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblLink.setForeground(new java.awt.Color(233, 232, 231));
        lblLink.setText("Link");

        txtFldReleasedYear.setBackground(new java.awt.Color(32, 38, 46));
        txtFldReleasedYear.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldReleasedYear.setForeground(new java.awt.Color(233, 232, 231));
        txtFldReleasedYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldReleasedYear.setPreferredSize(new java.awt.Dimension(84, 42));

        lblReleasedDate.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblReleasedDate.setForeground(new java.awt.Color(233, 232, 231));
        lblReleasedDate.setText("Released Date");

        txtFldReleasedMonth.setBackground(new java.awt.Color(32, 38, 46));
        txtFldReleasedMonth.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldReleasedMonth.setForeground(new java.awt.Color(233, 232, 231));
        txtFldReleasedMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldReleasedMonth.setPreferredSize(new java.awt.Dimension(64, 42));

        txtFldReleasedDay.setBackground(new java.awt.Color(32, 38, 46));
        txtFldReleasedDay.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldReleasedDay.setForeground(new java.awt.Color(233, 232, 231));
        txtFldReleasedDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldReleasedDay.setPreferredSize(new java.awt.Dimension(64, 42));

        lblSlash1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblSlash1.setForeground(new java.awt.Color(233, 232, 231));
        lblSlash1.setText("/");

        lblSlash2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblSlash2.setForeground(new java.awt.Color(233, 232, 231));
        lblSlash2.setText("/");

        radioBtnAction.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnAction.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnAction.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnAction.setText("Action");

        radioBtnAdventures.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnAdventures.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnAdventures.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnAdventures.setText("Adventures");

        radioBtnEducational.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnEducational.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnEducational.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnEducational.setText("Educational");

        radioBtnRolePlaying.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnRolePlaying.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnRolePlaying.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnRolePlaying.setText("Role-Playing");

        radioBtnRacing.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnRacing.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnRacing.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnRacing.setText("Racing/Driving");

        radioBtnSimulation.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnSimulation.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnSimulation.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnSimulation.setText("Simulation");

        radioBtnSports.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnSports.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnSports.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnSports.setText("Sports");

        radioBtnStrategy.setBackground(new java.awt.Color(145, 49, 117));
        radioBtnStrategy.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        radioBtnStrategy.setForeground(new java.awt.Color(233, 232, 231));
        radioBtnStrategy.setText("Strategy");

        btnAddGame.setBackground(new java.awt.Color(205, 88, 136));
        btnAddGame.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnAddGame.setForeground(new java.awt.Color(32, 38, 46));
        btnAddGame.setText("Add Game");
        btnAddGame.setBorder(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/closeIcon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddGamesLayout = new javax.swing.GroupLayout(pnlAddGames);
        pnlAddGames.setLayout(pnlAddGamesLayout);
        pnlAddGamesLayout.setHorizontalGroup(
            pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddGamesLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddGamesLayout.createSequentialGroup()
                        .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGameNum)
                            .addComponent(txtFldPublishers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPublishers)
                            .addComponent(txtFldMainDevelopers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainDevelopers)
                            .addComponent(txtFldGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGameTitle)
                            .addComponent(txtFldGameNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenres1)
                            .addComponent(lblGenres2)
                            .addComponent(comboBoxRating, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLink)
                            .addComponent(comboBoxPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReleasedDate)
                            .addGroup(pnlAddGamesLayout.createSequentialGroup()
                                .addComponent(txtFldReleasedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSlash1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFldReleasedMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSlash2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFldReleasedDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))
                    .addGroup(pnlAddGamesLayout.createSequentialGroup()
                        .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddGamesLayout.createSequentialGroup()
                                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnRacing)
                                    .addComponent(radioBtnSports))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAddGamesLayout.createSequentialGroup()
                                        .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioBtnRolePlaying)
                                            .addComponent(radioBtnAdventures))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioBtnEducational)
                                            .addGroup(pnlAddGamesLayout.createSequentialGroup()
                                                .addComponent(radioBtnSimulation)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(radioBtnStrategy))
                                .addGap(8, 8, 8))
                            .addComponent(lblGenres)
                            .addComponent(radioBtnAction)
                            .addGroup(pnlAddGamesLayout.createSequentialGroup()
                                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        pnlAddGamesLayout.setVerticalGroup(
            pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddGamesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddGamesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddGamesLayout.createSequentialGroup()
                        .addComponent(lblGameNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldGameNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGameTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldGameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(lblMainDevelopers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldMainDevelopers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPublishers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldPublishers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddGamesLayout.createSequentialGroup()
                        .addComponent(lblGenres1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxPlatform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGenres2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxRating, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblReleasedDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFldReleasedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldReleasedMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldReleasedDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSlash1)
                            .addComponent(lblSlash2))))
                .addGap(18, 18, 18)
                .addComponent(lblGenres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnAction)
                    .addComponent(radioBtnAdventures)
                    .addComponent(radioBtnEducational))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnRolePlaying)
                    .addComponent(radioBtnSimulation)
                    .addComponent(radioBtnRacing)
                    .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnSports)
                    .addComponent(radioBtnStrategy))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAddGames, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlAddGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gameSpace.closeWindow();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGame;
    private javax.swing.JComboBox<String> comboBoxPlatform;
    private javax.swing.JComboBox<String> comboBoxRating;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGameNum;
    private javax.swing.JLabel lblGameTitle;
    private javax.swing.JLabel lblGenres;
    private javax.swing.JLabel lblGenres1;
    private javax.swing.JLabel lblGenres2;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblMainDevelopers;
    private javax.swing.JLabel lblPublishers;
    private javax.swing.JLabel lblReleasedDate;
    private javax.swing.JLabel lblSlash1;
    private javax.swing.JLabel lblSlash2;
    private javax.swing.JPanel pnlAddGames;
    private javax.swing.JRadioButton radioBtnAction;
    private javax.swing.JRadioButton radioBtnAdventures;
    private javax.swing.JRadioButton radioBtnEducational;
    private javax.swing.JRadioButton radioBtnRacing;
    private javax.swing.JRadioButton radioBtnRolePlaying;
    private javax.swing.JRadioButton radioBtnSimulation;
    private javax.swing.JRadioButton radioBtnSports;
    private javax.swing.JRadioButton radioBtnStrategy;
    private javax.swing.JTextField txtFldGameNum;
    private javax.swing.JTextField txtFldGameTitle;
    private javax.swing.JTextField txtFldLink;
    private javax.swing.JTextField txtFldMainDevelopers;
    private javax.swing.JTextField txtFldPublishers;
    private javax.swing.JTextField txtFldReleasedDay;
    private javax.swing.JTextField txtFldReleasedMonth;
    private javax.swing.JTextField txtFldReleasedYear;
    // End of variables declaration//GEN-END:variables
}
