/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gamespace.views;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author ilust
 */
public class GameSpace extends javax.swing.JFrame {

    /**
     * Creates new form GameSpace
     */
    public GameSpace() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainLogIn = new javax.swing.JPanel();
        pnlWelcomeLogIn = new RoundedPanel(80,new Color(145, 49, 117));
        pnlLogInBorder = new RoundedPanel(80,new Color(233, 232, 231) );
        pnlLogIn = new RoundedPanel(70,new Color(32, 38, 46));
        lblLogInTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        txtFldPassword = new javax.swing.JPasswordField();
        lblForgotPassword = new javax.swing.JLabel();
        pnlLogInbtn = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JButton();
        lblHaveAccount = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogInBackground = new javax.swing.JLabel();
        pnlWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblWlcPgLogo = new javax.swing.JLabel();
        lblWelcomePageImg = new javax.swing.JLabel();

        pnlMainLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlWelcomeLogIn.setBackground(new java.awt.Color(145, 49, 117));
        pnlWelcomeLogIn.setPreferredSize(new java.awt.Dimension(1280, 700));

        pnlLogInBorder.setBackground(new java.awt.Color(233, 232, 231));
        pnlLogInBorder.setPreferredSize(new java.awt.Dimension(650, 700));
        pnlLogInBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogIn.setBackground(new java.awt.Color(32, 38, 46));
        pnlLogIn.setPreferredSize(new java.awt.Dimension(640, 700));

        lblLogInTitle.setBackground(new java.awt.Color(233, 232, 231));
        lblLogInTitle.setFont(new java.awt.Font("Pixelify Sans", 0, 32)); // NOI18N
        lblLogInTitle.setForeground(new java.awt.Color(233, 232, 231));
        lblLogInTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogInTitle.setText("Log-In To GameSpace");

        lblUsername.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(233, 232, 231));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(233, 232, 231));
        lblPassword.setText("Password");

        txtFldUsername.setBackground(new java.awt.Color(145, 49, 117));
        txtFldUsername.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldUsername.setForeground(new java.awt.Color(233, 232, 231));
        txtFldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldUsername.setPreferredSize(new java.awt.Dimension(368, 42));
        txtFldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUsernameActionPerformed(evt);
            }
        });

        txtFldPassword.setBackground(new java.awt.Color(145, 49, 117));
        txtFldPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldPassword.setForeground(new java.awt.Color(233, 232, 231));
        txtFldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldPassword.setPreferredSize(new java.awt.Dimension(368, 42));
        txtFldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldPasswordActionPerformed(evt);
            }
        });

        lblForgotPassword.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(233, 232, 231));
        lblForgotPassword.setText("Forgot Password?");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlLogInbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        pnlLogInbtn.setPreferredSize(new java.awt.Dimension(147, 43));

        btnLogIn.setBackground(new java.awt.Color(32, 38, 46));
        btnLogIn.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(233, 232, 231));
        btnLogIn.setText("Log-In");
        btnLogIn.setBorder(null);
        btnLogIn.setBorderPainted(false);
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.setPreferredSize(new java.awt.Dimension(141, 37));

        javax.swing.GroupLayout pnlLogInbtnLayout = new javax.swing.GroupLayout(pnlLogInbtn);
        pnlLogInbtn.setLayout(pnlLogInbtnLayout);
        pnlLogInbtnLayout.setHorizontalGroup(
            pnlLogInbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLogInbtnLayout.setVerticalGroup(
            pnlLogInbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblHaveAccount.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHaveAccount.setForeground(new java.awt.Color(233, 232, 231));
        lblHaveAccount.setText("Don't have a Account?");

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addComponent(pnlLogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(lblHaveAccount))
                    .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblForgotPassword)
                        .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPassword)
                        .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsername)
                        .addComponent(lblLogInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlLogInLayout.setVerticalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(lblLogInTitle)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPassword)
                .addGap(18, 18, 18)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHaveAccount)
                    .addComponent(pnlLogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pnlLogInBorder.add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logoGameSpaceResized.png"))); // NOI18N

        javax.swing.GroupLayout pnlWelcomeLogInLayout = new javax.swing.GroupLayout(pnlWelcomeLogIn);
        pnlWelcomeLogIn.setLayout(pnlWelcomeLogInLayout);
        pnlWelcomeLogInLayout.setHorizontalGroup(
            pnlWelcomeLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLogInLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(78, 78, 78)
                .addComponent(pnlLogInBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlWelcomeLogInLayout.setVerticalGroup(
            pnlWelcomeLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLogInLayout.createSequentialGroup()
                .addComponent(pnlLogInBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlWelcomeLogInLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMainLogIn.add(pnlWelcomeLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 1280, -1));

        lblLogInBackground.setBackground(new java.awt.Color(145, 49, 117));
        lblLogInBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/loginpage Background.png"))); // NOI18N
        pnlMainLogIn.add(lblLogInBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlWelcome.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(233, 232, 231));
        lblWelcome.setText("WELCOME TO");
        pnlWelcome.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, -1, -1));

        btnContinue.setBackground(new java.awt.Color(233, 232, 231));
        btnContinue.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(32, 38, 46));
        btnContinue.setText("Continue");
        btnContinue.setBorder(null);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        pnlWelcome.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 930, 140, 30));

        lblWlcPgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcPgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logoGameSpaceResized1.png"))); // NOI18N
        pnlWelcome.add(lblWlcPgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 1920, 1070));

        lblWelcomePageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/welcomePage.png"))); // NOI18N
        pnlWelcome.add(lblWelcomePageImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldUsernameActionPerformed

    private void txtFldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldPasswordActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSpace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblHaveAccount;
    private javax.swing.JLabel lblLogInBackground;
    private javax.swing.JLabel lblLogInTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomePageImg;
    private javax.swing.JLabel lblWlcPgLogo;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPanel pnlLogInBorder;
    private javax.swing.JPanel pnlLogInbtn;
    private javax.swing.JPanel pnlMainLogIn;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JPanel pnlWelcomeLogIn;
    private javax.swing.JPasswordField txtFldPassword;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables

class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
            setOpaque(false);
        }
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            
            graphics.setColor(backgroundColor != null ? backgroundColor : getBackground());
            graphics.fillRoundRect(0, 0, width, height, arcs.width, arcs.height);             
        }
    }
}
