/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gamespace.views;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Ronish Prajapati
 * LmuID: 23048584
 */
public class GameSpace extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form GameSpace
     */
    public GameSpace() {
        setUndecorated(true);
        initComponents();
        //initializeLayout();
        //startProgress();
    }

    private void initializeTools() {

    }

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        getContentPane().add(pnlWelcome, "WelcomeScreen");
        getContentPane().add(pnlMainLogIn, "LogInScreen");

        cardLayout.show(getContentPane(), "WelcomeScreen");
    }

    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(15); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarWelcomeScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LogInScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }

    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void closeWindow(){
        WindowEvent close= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close);
    }
    
    private void minimizeWindow(){
        setExtendedState(JFrame.ICONIFIED);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainLogIn = new javax.swing.JPanel();
        btnMinimizeLogIn = new javax.swing.JButton();
        btnCloseLogIn = new javax.swing.JButton();
        pnlWelcomeLogIn = new CustomRoundedPanel(80,new Color(145, 49, 117));
        pnlLogInBorder = new CustomRoundedPanel(80,new Color(233, 232, 231) );
        pnlLogIn = new CustomRoundedPanel(70,new Color(32, 38, 46));
        lblLogInTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        txtFldPassword = new javax.swing.JPasswordField();
        lblForgotPassword = new javax.swing.JLabel();
        pnlLogInbtn = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JButton();
        lblHaveAccount = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogInBackground = new javax.swing.JLabel();
        pnlWelcome = new javax.swing.JPanel();
        pgBarWelcomeScreen = new javax.swing.JProgressBar();
        lblWelcome = new javax.swing.JLabel();
        lblWlcPgLogo = new javax.swing.JLabel();
        lblWelcomePageImg = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        lblAdminIcon = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnAddGames = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlSearchBar = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        pnlDashboardBg = new javax.swing.JLabel();

        pnlMainLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizeLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/minmize-icon.png"))); // NOI18N
        btnMinimizeLogIn.setBorder(null);
        btnMinimizeLogIn.setBorderPainted(false);
        btnMinimizeLogIn.setContentAreaFilled(false);
        btnMinimizeLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeLogInActionPerformed(evt);
            }
        });
        pnlMainLogIn.add(btnMinimizeLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 10, -1, -1));

        btnCloseLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/closeIcon.png"))); // NOI18N
        btnCloseLogIn.setBorder(null);
        btnCloseLogIn.setBorderPainted(false);
        btnCloseLogIn.setContentAreaFilled(false);
        btnCloseLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseLogInActionPerformed(evt);
            }
        });
        pnlMainLogIn.add(btnCloseLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 10, -1, -1));

        pnlWelcomeLogIn.setBackground(new java.awt.Color(145, 49, 117));
        pnlWelcomeLogIn.setPreferredSize(new java.awt.Dimension(1280, 700));

        pnlLogInBorder.setBackground(new java.awt.Color(233, 232, 231));
        pnlLogInBorder.setPreferredSize(new java.awt.Dimension(650, 700));
        pnlLogInBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogIn.setBackground(new java.awt.Color(32, 38, 46));
        pnlLogIn.setPreferredSize(new java.awt.Dimension(640, 700));

        lblLogInTitle.setBackground(new java.awt.Color(233, 232, 231));
        lblLogInTitle.setFont(new java.awt.Font("Pixelify Sans", 0, 32)); // NOI18N
        lblLogInTitle.setForeground(new java.awt.Color(233, 232, 231));
        lblLogInTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogInTitle.setText("Log-In To GameSpace");

        lblUsername.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(233, 232, 231));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(233, 232, 231));
        lblPassword.setText("Password");

        txtFldUsername.setBackground(new java.awt.Color(145, 49, 117));
        txtFldUsername.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldUsername.setForeground(new java.awt.Color(233, 232, 231));
        txtFldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldUsername.setPreferredSize(new java.awt.Dimension(368, 42));

        txtFldPassword.setBackground(new java.awt.Color(145, 49, 117));
        txtFldPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldPassword.setForeground(new java.awt.Color(233, 232, 231));
        txtFldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldPassword.setPreferredSize(new java.awt.Dimension(368, 42));

        lblForgotPassword.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(233, 232, 231));
        lblForgotPassword.setText("Forgot Password?");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlLogInbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        pnlLogInbtn.setPreferredSize(new java.awt.Dimension(147, 43));

        btnLogIn.setBackground(new java.awt.Color(32, 38, 46));
        btnLogIn.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(233, 232, 231));
        btnLogIn.setText("Log-In");
        btnLogIn.setBorder(null);
        btnLogIn.setBorderPainted(false);
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.setPreferredSize(new java.awt.Dimension(141, 37));

        javax.swing.GroupLayout pnlLogInbtnLayout = new javax.swing.GroupLayout(pnlLogInbtn);
        pnlLogInbtn.setLayout(pnlLogInbtnLayout);
        pnlLogInbtnLayout.setHorizontalGroup(
            pnlLogInbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLogInbtnLayout.setVerticalGroup(
            pnlLogInbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblHaveAccount.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHaveAccount.setForeground(new java.awt.Color(233, 232, 231));
        lblHaveAccount.setText("Don't have a Account?");

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addComponent(pnlLogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(lblHaveAccount))
                    .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblForgotPassword)
                        .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPassword)
                        .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsername)
                        .addComponent(lblLogInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        pnlLogInLayout.setVerticalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblLogInTitle)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPassword)
                .addGap(18, 18, 18)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHaveAccount)
                    .addComponent(pnlLogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pnlLogInBorder.add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logoGameSpaceResized.png"))); // NOI18N

        javax.swing.GroupLayout pnlWelcomeLogInLayout = new javax.swing.GroupLayout(pnlWelcomeLogIn);
        pnlWelcomeLogIn.setLayout(pnlWelcomeLogInLayout);
        pnlWelcomeLogInLayout.setHorizontalGroup(
            pnlWelcomeLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLogInLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(78, 78, 78)
                .addComponent(pnlLogInBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlWelcomeLogInLayout.setVerticalGroup(
            pnlWelcomeLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLogInLayout.createSequentialGroup()
                .addComponent(pnlLogInBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlWelcomeLogInLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMainLogIn.add(pnlWelcomeLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 1280, -1));

        lblLogInBackground.setBackground(new java.awt.Color(145, 49, 117));
        lblLogInBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/loginpage Background.png"))); // NOI18N
        pnlMainLogIn.add(lblLogInBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlWelcome.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgBarWelcomeScreen.setStringPainted(true);
        pgBarWelcomeScreen.setBackground(new java.awt.Color(32, 38, 46));
        pgBarWelcomeScreen.setForeground(new java.awt.Color(145, 49, 117));
        pgBarWelcomeScreen.setBorder(null);
        pgBarWelcomeScreen.setBorderPainted(false);
        pgBarWelcomeScreen.setPreferredSize(new java.awt.Dimension(1920, 4));
        pnlWelcome.add(pgBarWelcomeScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 930, 1940, 10));

        lblWelcome.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(233, 232, 231));
        lblWelcome.setText("WELCOME TO");
        pnlWelcome.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, -1, -1));

        lblWlcPgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcPgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logoGameSpaceResized1.png"))); // NOI18N
        lblWlcPgLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlWelcome.add(lblWlcPgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 1920, 1070));

        lblWelcomePageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/welcomePage.png"))); // NOI18N
        pnlWelcome.add(lblWelcomePageImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAdmin.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidebar.setBackground(new java.awt.Color(32, 38, 46));

        lblAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/crown.png"))); // NOI18N

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);

        btnAddGames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/plus.png"))); // NOI18N
        btnAddGames.setBorder(null);
        btnAddGames.setBorderPainted(false);
        btnAddGames.setContentAreaFilled(false);
        btnAddGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGamesActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logout.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAdminIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAdminIcon)
                .addGap(301, 301, 301)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddGames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pnlAdmin.add(pnlSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 1080));

        pnlSearchBar.setBackground(new java.awt.Color(145, 49, 117));

        javax.swing.GroupLayout pnlSearchBarLayout = new javax.swing.GroupLayout(pnlSearchBar);
        pnlSearchBar.setLayout(pnlSearchBarLayout);
        pnlSearchBarLayout.setHorizontalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1820, Short.MAX_VALUE)
        );
        pnlSearchBarLayout.setVerticalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlAdmin.add(pnlSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1820, -1));

        pnlDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboardBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/pgBackground.png"))); // NOI18N
        pnlDashboard.add(pnlDashboardBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlAdmin.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 1820, 980));

        getContentPane().add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseLogInActionPerformed
        // TODO add your handling code here:
        closeWindow();
    }//GEN-LAST:event_btnCloseLogInActionPerformed

    private void btnMinimizeLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeLogInActionPerformed
        // TODO add your handling code here:
        minimizeWindow();
    }//GEN-LAST:event_btnMinimizeLogInActionPerformed

    private void btnAddGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        GameSpace app = new GameSpace();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSpace().setVisible(true);
            }
        });

        app.startProgress();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGames;
    private javax.swing.JButton btnCloseLogIn;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnMinimizeLogIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAdminIcon;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblHaveAccount;
    private javax.swing.JLabel lblLogInBackground;
    private javax.swing.JLabel lblLogInTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomePageImg;
    private javax.swing.JLabel lblWlcPgLogo;
    private javax.swing.JProgressBar pgBarWelcomeScreen;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JLabel pnlDashboardBg;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPanel pnlLogInBorder;
    private javax.swing.JPanel pnlLogInbtn;
    private javax.swing.JPanel pnlMainLogIn;
    private javax.swing.JPanel pnlSearchBar;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JPanel pnlWelcomeLogIn;
    private javax.swing.JPasswordField txtFldPassword;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables

}
