
package com.gamespace.views;

import com.gamespace.model.GameModel;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronish Prajapati
 * LmuID: 23048584
 */
public class GameSpace extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;
    private List<GameModel> gameList;

    /**
     * Creates new form GameSpace
     */
    public GameSpace() {
        setUndecorated(true);
        initComponents();
        initializeLayout();
        initializeTools();
        initializeData();
        startProgress();
        
    }

    private void initializeTools() {
        gameList = new LinkedList();
    }

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        getContentPane().add(pnlWelcome, "WelcomeScreen");
        getContentPane().add(pnlMainLogIn, "LogInScreen");
        getContentPane().add(pnlAdmin, "AdminScreen");

        cardLayout.show(getContentPane(), "WelcomeScreen");
    }
    
    private void initializeData(){
        gameList = new LinkedList();
        ArrayList<String> cars = new ArrayList<String>();
        cars.add("Volvo");
        cars.add("BMW");
        cars.add("Ford");
       
        
        addGamesToTable(new GameModel(1,"Counter Strike",cars,"Prajapati","asdf",cars,6,"adfs"));
    }

    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(15); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarWelcomeScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LogInScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }

    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void closeWindow(){
        WindowEvent close= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close);
    }
    
    private void minimizeWindow(){
        setExtendedState(JFrame.ICONIFIED);
    }
    
    private void logout(){
        loadScreen("LogInScreen");
    }
    
    private void addGamesToTable(GameModel game){
        gameList.add(game);
        DefaultTableModel model = (DefaultTableModel) tblGameData.getModel();
        
        model.addRow(new Object[]{
            game.getGameNum(),
            game.getGameName(),
            game.getMainDevelopers(),
            game.getPublishers(),
            game.getReleasedDate(),
            game.getRating(),
            game.getLink()
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainLogIn = new javax.swing.JPanel();
        btnMinimizeLogIn = new javax.swing.JButton();
        btnCloseLogIn = new javax.swing.JButton();
        pnlWelcomeLogIn = new CustomRoundedPanel(80,new Color(145, 49, 117));
        pnlLogInBorder = new CustomRoundedPanel(80,new Color(233, 232, 231) );
        pnlLogIn = new CustomRoundedPanel(70,new Color(32, 38, 46));
        lblLogInTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        txtFldPassword = new javax.swing.JPasswordField();
        lblForgotPassword = new javax.swing.JLabel();
        pnlLogInbtn = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JButton();
        lblHaveAccount = new javax.swing.JLabel();
        lblLoginError = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogInBackground = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        lblAdminIcon = new javax.swing.JLabel();
        btnLogoutAdmin = new javax.swing.JButton();
        pnlSearchBar = new javax.swing.JPanel();
        lblLogoAdmin = new javax.swing.JLabel();
        txtFldSearchAdmin = new javax.swing.JTextField();
        btnCloseWinAdmin = new javax.swing.JButton();
        btnMinimizeWinAdmin = new javax.swing.JButton();
        btnFilter = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        divider = new javax.swing.JPanel();
        pnlGameData = new javax.swing.JPanel();
        lblGameData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGameData = new javax.swing.JTable();
        btnAddGames = new javax.swing.JButton();
        btnRemoveGames = new javax.swing.JButton();
        btnUpdateGames = new javax.swing.JButton();
        pnlTotalAdmin = new CustomRoundedPanel(80, new Color(145,49,117));
        lblTotalAdmin = new javax.swing.JLabel();
        lblAdminNum = new javax.swing.JLabel();
        lblAdminIC = new javax.swing.JLabel();
        pnlTotalUsers = new CustomRoundedPanel(80, new Color(145,49,117));
        lblTotalUsers = new javax.swing.JLabel();
        lblUsersNum = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        pnlTotalGames = new CustomRoundedPanel(80, new Color(145,49,117));
        lblTotalGames = new javax.swing.JLabel();
        lblGamesNum = new javax.swing.JLabel();
        lblGameIcon = new javax.swing.JLabel();
        pnlDashboardBg = new javax.swing.JLabel();
        pnlWelcome = new javax.swing.JPanel();
        pgBarWelcomeScreen = new javax.swing.JProgressBar();
        lblWelcome = new javax.swing.JLabel();
        lblWlcPgLogo = new javax.swing.JLabel();
        lblWelcomePageImg = new javax.swing.JLabel();

        pnlMainLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizeLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/minmize-icon.png"))); // NOI18N
        btnMinimizeLogIn.setBorder(null);
        btnMinimizeLogIn.setBorderPainted(false);
        btnMinimizeLogIn.setContentAreaFilled(false);
        btnMinimizeLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeLogInActionPerformed(evt);
            }
        });
        pnlMainLogIn.add(btnMinimizeLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, -1, -1));

        btnCloseLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/closeIcon.png"))); // NOI18N
        btnCloseLogIn.setBorder(null);
        btnCloseLogIn.setBorderPainted(false);
        btnCloseLogIn.setContentAreaFilled(false);
        btnCloseLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseLogInActionPerformed(evt);
            }
        });
        pnlMainLogIn.add(btnCloseLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 10, -1, -1));

        pnlWelcomeLogIn.setBackground(new java.awt.Color(145, 49, 117));
        pnlWelcomeLogIn.setPreferredSize(new java.awt.Dimension(1280, 700));

        pnlLogInBorder.setBackground(new java.awt.Color(233, 232, 231));
        pnlLogInBorder.setPreferredSize(new java.awt.Dimension(650, 700));
        pnlLogInBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogIn.setBackground(new java.awt.Color(32, 38, 46));
        pnlLogIn.setPreferredSize(new java.awt.Dimension(640, 700));

        lblLogInTitle.setBackground(new java.awt.Color(233, 232, 231));
        lblLogInTitle.setFont(new java.awt.Font("Pixelify Sans", 0, 32)); // NOI18N
        lblLogInTitle.setForeground(new java.awt.Color(233, 232, 231));
        lblLogInTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogInTitle.setText("Log-In To GameSpace");

        lblUsername.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(233, 232, 231));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(233, 232, 231));
        lblPassword.setText("Password");

        txtFldUsername.setBackground(new java.awt.Color(145, 49, 117));
        txtFldUsername.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldUsername.setForeground(new java.awt.Color(233, 232, 231));
        txtFldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldUsername.setPreferredSize(new java.awt.Dimension(368, 42));

        txtFldPassword.setBackground(new java.awt.Color(145, 49, 117));
        txtFldPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txtFldPassword.setForeground(new java.awt.Color(233, 232, 231));
        txtFldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        txtFldPassword.setPreferredSize(new java.awt.Dimension(368, 42));

        lblForgotPassword.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(233, 232, 231));
        lblForgotPassword.setText("Forgot Password?");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnlLogInbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 232, 231), 3));
        pnlLogInbtn.setPreferredSize(new java.awt.Dimension(147, 43));

        btnLogIn.setBackground(new java.awt.Color(32, 38, 46));
        btnLogIn.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(233, 232, 231));
        btnLogIn.setText("Log-In");
        btnLogIn.setBorder(null);
        btnLogIn.setBorderPainted(false);
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.setPreferredSize(new java.awt.Dimension(141, 37));
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogInbtnLayout = new javax.swing.GroupLayout(pnlLogInbtn);
        pnlLogInbtn.setLayout(pnlLogInbtnLayout);
        pnlLogInbtnLayout.setHorizontalGroup(
            pnlLogInbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLogInbtnLayout.setVerticalGroup(
            pnlLogInbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblHaveAccount.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHaveAccount.setForeground(new java.awt.Color(233, 232, 231));
        lblHaveAccount.setText("Don't have a Account?");

        lblLoginError.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(217, 84, 79));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLogInLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addComponent(pnlLogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(lblHaveAccount))
                            .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblForgotPassword)
                                .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPassword)
                                .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUsername)
                                .addComponent(lblLogInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        pnlLogInLayout.setVerticalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblLogInTitle)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPassword)
                .addGap(18, 18, 18)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHaveAccount)
                    .addComponent(pnlLogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLoginError)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pnlLogInBorder.add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logoGameSpaceResized.png"))); // NOI18N

        javax.swing.GroupLayout pnlWelcomeLogInLayout = new javax.swing.GroupLayout(pnlWelcomeLogIn);
        pnlWelcomeLogIn.setLayout(pnlWelcomeLogInLayout);
        pnlWelcomeLogInLayout.setHorizontalGroup(
            pnlWelcomeLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLogInLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(78, 78, 78)
                .addComponent(pnlLogInBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlWelcomeLogInLayout.setVerticalGroup(
            pnlWelcomeLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLogInLayout.createSequentialGroup()
                .addComponent(pnlLogInBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlWelcomeLogInLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMainLogIn.add(pnlWelcomeLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 1280, -1));

        lblLogInBackground.setBackground(new java.awt.Color(145, 49, 117));
        lblLogInBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/loginpage Background.png"))); // NOI18N
        pnlMainLogIn.add(lblLogInBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlAdmin.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidebar.setBackground(new java.awt.Color(32, 38, 46));
        pnlSidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        pnlSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/crown.png"))); // NOI18N

        btnLogoutAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logout.png"))); // NOI18N
        btnLogoutAdmin.setBorder(null);
        btnLogoutAdmin.setBorderPainted(false);
        btnLogoutAdmin.setContentAreaFilled(false);
        btnLogoutAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogoutAdmin)
                    .addComponent(lblAdminIcon))
                .addGap(21, 21, 21))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAdminIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 942, Short.MAX_VALUE)
                .addComponent(btnLogoutAdmin)
                .addGap(22, 22, 22))
        );

        pnlAdmin.add(pnlSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 120, 1100));

        pnlSearchBar.setBackground(new java.awt.Color(145, 49, 117));
        pnlSearchBar.setPreferredSize(new java.awt.Dimension(1820, 100));

        lblLogoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/Untitled-1.png"))); // NOI18N

        txtFldSearchAdmin.setBackground(new java.awt.Color(233, 232, 231));
        txtFldSearchAdmin.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtFldSearchAdmin.setForeground(new java.awt.Color(145, 49, 117));
        txtFldSearchAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 38, 46), 5));
        txtFldSearchAdmin.setPreferredSize(new java.awt.Dimension(1275, 45));

        btnCloseWinAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/closeIcon.png"))); // NOI18N
        btnCloseWinAdmin.setBorder(null);
        btnCloseWinAdmin.setBorderPainted(false);
        btnCloseWinAdmin.setContentAreaFilled(false);
        btnCloseWinAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWinAdminActionPerformed(evt);
            }
        });

        btnMinimizeWinAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/minmize-icon.png"))); // NOI18N
        btnMinimizeWinAdmin.setBorder(null);
        btnMinimizeWinAdmin.setBorderPainted(false);
        btnMinimizeWinAdmin.setContentAreaFilled(false);
        btnMinimizeWinAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeWinAdminActionPerformed(evt);
            }
        });

        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/filter.png"))); // NOI18N

        javax.swing.GroupLayout pnlSearchBarLayout = new javax.swing.GroupLayout(pnlSearchBar);
        pnlSearchBar.setLayout(pnlSearchBarLayout);
        pnlSearchBarLayout.setHorizontalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoAdmin)
                .addGap(26, 26, 26)
                .addComponent(txtFldSearchAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnFilter)
                .addGap(18, 18, 18)
                .addComponent(btnMinimizeWinAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCloseWinAdmin)
                .addContainerGap())
        );
        pnlSearchBarLayout.setVerticalGroup(
            pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBarLayout.createSequentialGroup()
                .addGroup(pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogoAdmin)
                            .addComponent(btnCloseWinAdmin)
                            .addComponent(btnMinimizeWinAdmin)))
                    .addGroup(pnlSearchBarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlSearchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFilter)
                            .addComponent(txtFldSearchAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlAdmin.add(pnlSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1820, -1));

        pnlDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        divider.setBackground(new java.awt.Color(233, 232, 231));
        divider.setPreferredSize(new java.awt.Dimension(1800, 5));

        javax.swing.GroupLayout dividerLayout = new javax.swing.GroupLayout(divider);
        divider.setLayout(dividerLayout);
        dividerLayout.setHorizontalGroup(
            dividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1800, Short.MAX_VALUE)
        );
        dividerLayout.setVerticalGroup(
            dividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlDashboard.add(divider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1800, 10));

        pnlGameData.setBackground(new java.awt.Color(32, 38, 46));
        pnlGameData.setOpaque(false);

        lblGameData.setFont(new java.awt.Font("Pixelify Sans", 0, 24)); // NOI18N
        lblGameData.setForeground(new java.awt.Color(233, 232, 231));
        lblGameData.setText("Game Data");

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBackground(null);
        jScrollPane1.getViewport().setBorder(null);

        tblGameData.setOpaque(false);
        ((DefaultTableCellRenderer)tblGameData.getDefaultRenderer(Object.class)).setOpaque(false);
        tblGameData.setShowGrid(false);
        tblGameData.getTableHeader().setFont(new java.awt.Font("Roboto", 0,16 ));
        tblGameData.getTableHeader().setOpaque(false);
        tblGameData.getTableHeader().setBackground(new Color(145,49,117));
        tblGameData.getTableHeader().setForeground(new Color(233,232,231));
        tblGameData.setRowHeight(40);
        tblGameData.setBorder(null);
        tblGameData.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        tblGameData.setForeground(new java.awt.Color(32, 38, 46));
        tblGameData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Game No.", "Game Title", "Main Developers", "Publisher", "Released Date", "Genres", "Rating", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGameData.setFocusable(false);
        tblGameData.setRowHeight(40);
        tblGameData.setSelectionBackground(new java.awt.Color(145, 49, 117));
        tblGameData.setSelectionForeground(new java.awt.Color(233, 232, 231));
        tblGameData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblGameData.setShowGrid(false);
        tblGameData.setShowHorizontalLines(true);
        tblGameData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblGameData);

        btnAddGames.setBackground(new java.awt.Color(145, 49, 117));
        btnAddGames.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnAddGames.setForeground(new java.awt.Color(233, 232, 231));
        btnAddGames.setText("Add Games");
        btnAddGames.setBorder(null);
        btnAddGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGamesActionPerformed(evt);
            }
        });

        btnRemoveGames.setBackground(new java.awt.Color(145, 49, 117));
        btnRemoveGames.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnRemoveGames.setForeground(new java.awt.Color(233, 232, 231));
        btnRemoveGames.setText("Remove");
        btnRemoveGames.setBorder(null);

        btnUpdateGames.setBackground(new java.awt.Color(145, 49, 117));
        btnUpdateGames.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnUpdateGames.setForeground(new java.awt.Color(233, 232, 231));
        btnUpdateGames.setText("Update");
        btnUpdateGames.setBorder(null);

        javax.swing.GroupLayout pnlGameDataLayout = new javax.swing.GroupLayout(pnlGameData);
        pnlGameData.setLayout(pnlGameDataLayout);
        pnlGameDataLayout.setHorizontalGroup(
            pnlGameDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlGameDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlGameDataLayout.createSequentialGroup()
                        .addComponent(lblGameData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1261, Short.MAX_VALUE)
                        .addComponent(btnAddGames, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateGames, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveGames, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlGameDataLayout.setVerticalGroup(
            pnlGameDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameDataLayout.createSequentialGroup()
                .addGroup(pnlGameDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGameDataLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblGameData)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlGameDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddGames, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveGames, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateGames, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDashboard.add(pnlGameData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1790, 620));

        pnlTotalAdmin.setBackground(new java.awt.Color(145, 49, 117));

        lblTotalAdmin.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        lblTotalAdmin.setForeground(new java.awt.Color(233, 232, 231));
        lblTotalAdmin.setText("Total Users");

        lblAdminNum.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblAdminNum.setForeground(new java.awt.Color(233, 232, 231));
        lblAdminNum.setText("100");

        lblAdminIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/whiteCrown.png"))); // NOI18N

        javax.swing.GroupLayout pnlTotalAdminLayout = new javax.swing.GroupLayout(pnlTotalAdmin);
        pnlTotalAdmin.setLayout(pnlTotalAdminLayout);
        pnlTotalAdminLayout.setHorizontalGroup(
            pnlTotalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalAdminLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlTotalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalAdminLayout.createSequentialGroup()
                        .addComponent(lblAdminIC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdminNum)
                        .addGap(31, 31, 31))
                    .addGroup(pnlTotalAdminLayout.createSequentialGroup()
                        .addComponent(lblTotalAdmin)
                        .addContainerGap(151, Short.MAX_VALUE))))
        );
        pnlTotalAdminLayout.setVerticalGroup(
            pnlTotalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalAdminLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTotalAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlTotalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdminIC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );

        pnlDashboard.add(pnlTotalAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 60, -1, -1));

        pnlTotalUsers.setBackground(new java.awt.Color(145, 49, 117));

        lblTotalUsers.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        lblTotalUsers.setForeground(new java.awt.Color(233, 232, 231));
        lblTotalUsers.setText("Total Users");

        lblUsersNum.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblUsersNum.setForeground(new java.awt.Color(233, 232, 231));
        lblUsersNum.setText("100");

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/users.png"))); // NOI18N

        javax.swing.GroupLayout pnlTotalUsersLayout = new javax.swing.GroupLayout(pnlTotalUsers);
        pnlTotalUsers.setLayout(pnlTotalUsersLayout);
        pnlTotalUsersLayout.setHorizontalGroup(
            pnlTotalUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalUsersLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlTotalUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalUsersLayout.createSequentialGroup()
                        .addComponent(lblUserIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsersNum)
                        .addGap(31, 31, 31))
                    .addGroup(pnlTotalUsersLayout.createSequentialGroup()
                        .addComponent(lblTotalUsers)
                        .addContainerGap(151, Short.MAX_VALUE))))
        );
        pnlTotalUsersLayout.setVerticalGroup(
            pnlTotalUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalUsersLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTotalUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlTotalUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsersNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );

        pnlDashboard.add(pnlTotalUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        pnlTotalGames.setBackground(new java.awt.Color(145, 49, 117));

        lblTotalGames.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        lblTotalGames.setForeground(new java.awt.Color(233, 232, 231));
        lblTotalGames.setText("Total Games");

        lblGamesNum.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblGamesNum.setForeground(new java.awt.Color(233, 232, 231));
        lblGamesNum.setText("100");

        lblGameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/joystick.png"))); // NOI18N

        javax.swing.GroupLayout pnlTotalGamesLayout = new javax.swing.GroupLayout(pnlTotalGames);
        pnlTotalGames.setLayout(pnlTotalGamesLayout);
        pnlTotalGamesLayout.setHorizontalGroup(
            pnlTotalGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalGamesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlTotalGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalGamesLayout.createSequentialGroup()
                        .addComponent(lblGameIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGamesNum)
                        .addGap(31, 31, 31))
                    .addGroup(pnlTotalGamesLayout.createSequentialGroup()
                        .addComponent(lblTotalGames)
                        .addContainerGap(151, Short.MAX_VALUE))))
        );
        pnlTotalGamesLayout.setVerticalGroup(
            pnlTotalGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalGamesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTotalGames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlTotalGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGamesNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGameIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );

        pnlDashboard.add(pnlTotalGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 400, 210));

        pnlDashboardBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/pgBackground.png"))); // NOI18N
        pnlDashboardBg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDashboard.add(pnlDashboardBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlAdmin.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 1820, 980));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlWelcome.setPreferredSize(new java.awt.Dimension(1920, 1080));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgBarWelcomeScreen.setStringPainted(true);
        pgBarWelcomeScreen.setBackground(new java.awt.Color(32, 38, 46));
        pgBarWelcomeScreen.setForeground(new java.awt.Color(145, 49, 117));
        pgBarWelcomeScreen.setBorder(null);
        pgBarWelcomeScreen.setBorderPainted(false);
        pgBarWelcomeScreen.setPreferredSize(new java.awt.Dimension(1920, 4));
        pnlWelcome.add(pgBarWelcomeScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1070, 1920, 10));

        lblWelcome.setFont(new java.awt.Font("Pixelify Sans", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(233, 232, 231));
        lblWelcome.setText("WELCOME TO");
        pnlWelcome.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, -1, -1));

        lblWlcPgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWlcPgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/logoGameSpaceResized1.png"))); // NOI18N
        lblWlcPgLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlWelcome.add(lblWlcPgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 1920, 1070));

        lblWelcomePageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamespace/resources/welcomePage.png"))); // NOI18N
        pnlWelcome.add(lblWelcomePageImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseLogInActionPerformed
        // TODO add your handling code here:
        closeWindow();
    }//GEN-LAST:event_btnCloseLogInActionPerformed

    private void btnMinimizeLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeLogInActionPerformed
        // TODO add your handling code here:
        minimizeWindow();
    }//GEN-LAST:event_btnMinimizeLogInActionPerformed

    private void btnMinimizeWinAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeWinAdminActionPerformed
        // TODO add your handling code here:
        minimizeWindow();
    }//GEN-LAST:event_btnMinimizeWinAdminActionPerformed

    private void btnCloseWinAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWinAdminActionPerformed
        // TODO add your handling code here:
        closeWindow();
    }//GEN-LAST:event_btnCloseWinAdminActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        String username = "admin";
        String password = "admin";
        String usernametxt = txtFldUsername.getText();
        String passwordtxt = new String(txtFldPassword.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!usernametxt.equals("admin") || !passwordtxt.equals("admin")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            loadScreen("AdminScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnAddGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGamesActionPerformed
        // TODO add your handling code here:
        AddGamesFrame addgames=new AddGamesFrame();
        addgames.setVisible(true);
    }//GEN-LAST:event_btnAddGamesActionPerformed

    private void btnLogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutAdminActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_btnLogoutAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        GameSpace app = new GameSpace();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSpace().setVisible(true);
            }
        });

        app.startProgress();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGames;
    private javax.swing.JButton btnCloseLogIn;
    private javax.swing.JButton btnCloseWinAdmin;
    private javax.swing.JLabel btnFilter;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogoutAdmin;
    private javax.swing.JButton btnMinimizeLogIn;
    private javax.swing.JButton btnMinimizeWinAdmin;
    private javax.swing.JButton btnRemoveGames;
    private javax.swing.JButton btnUpdateGames;
    private javax.swing.JPanel divider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminIC;
    private javax.swing.JLabel lblAdminIcon;
    private javax.swing.JLabel lblAdminNum;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblGameData;
    private javax.swing.JLabel lblGameIcon;
    private javax.swing.JLabel lblGamesNum;
    private javax.swing.JLabel lblHaveAccount;
    private javax.swing.JLabel lblLogInBackground;
    private javax.swing.JLabel lblLogInTitle;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoAdmin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTotalAdmin;
    private javax.swing.JLabel lblTotalGames;
    private javax.swing.JLabel lblTotalUsers;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsersNum;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomePageImg;
    private javax.swing.JLabel lblWlcPgLogo;
    private javax.swing.JProgressBar pgBarWelcomeScreen;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JLabel pnlDashboardBg;
    private javax.swing.JPanel pnlGameData;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPanel pnlLogInBorder;
    private javax.swing.JPanel pnlLogInbtn;
    private javax.swing.JPanel pnlMainLogIn;
    private javax.swing.JPanel pnlSearchBar;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlTotalAdmin;
    private javax.swing.JPanel pnlTotalGames;
    private javax.swing.JPanel pnlTotalUsers;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JPanel pnlWelcomeLogIn;
    private javax.swing.JTable tblGameData;
    private javax.swing.JPasswordField txtFldPassword;
    private javax.swing.JTextField txtFldSearchAdmin;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables

}
